In [1]:
import pandas as pd
import numpy as np
import os
import sys 
from datetime import datetime
sys.path.append(f'../../Functions') 
from reader import fetch, LmpGP_file_reader
from CNN_pretreatment import Datafile_to_grids

In [2]:
# 示例数据
GP_data = np.array([
    [1, 1, 0.3, 0.3, 0.3],
    [2, 1, 0.6, 0.6, 0.6]
])

grid_size   = (4, 4, 4)  # 网格划分的尺寸
limits      = {'x':[0, 1], 'y':[0, 1], 'z':[0, 1]}
limits_new  = {'x':[0, 4], 'y':[0, 4], 'z':[0, 4]}

In [3]:
# 运行程序
aligner = Datafile_to_grids(GP_data,
                            grid_size,
                            limits,
                            limits_new)

Grid counts shape: (4, 4, 4)
[[[2. 2. 2. 2.]
  [2. 2. 2. 2.]
  [2. 2. 2. 2.]
  [2. 2. 2. 2.]]

 [[2. 2. 2. 2.]
  [2. 2. 2. 2.]
  [2. 2. 2. 2.]
  [2. 2. 2. 2.]]

 [[2. 2. 2. 2.]
  [2. 2. 2. 2.]
  [2. 2. 2. 2.]
  [2. 2. 2. 2.]]

 [[2. 2. 2. 2.]
  [2. 2. 2. 2.]
  [2. 2. 2. 2.]
  [2. 2. 2. 2.]]]


In [4]:
a = (3,3,3)
b = np.zeros(a)
b

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])